version: '3'

services:
  posgres_db:
    image: postgres
    container_name: postgres
    ports:
      - '5400:5432'
    environment:
      - POSTGRES_USER=symfony
      - POSTGRES_PASSWORD=symfony
      - POSTGRES_DB=space_db
    volumes:
      - ./postgres.conf:/etc/postgresql/postgresql.conf
    restart: always

  php:
    container_name: php
    build:
      context: ./php
    ports:
      - '9000:9000'
    volumes:
      - ./app:/var/www/symfony_docker
    depends_on:
      - posgres_db

  nginx:
    build: nginx
    ports:
      - '8080:80'
    links:
      - php
    volumes:
      - ./logs/nginx/:/var/log/nginx:cached
    depends_on:
      - php
      - posgres_db